### PR TITLE
Push mqtt credential into vault

### LINKED ISSUE #376: [Security] Subscriber didn't receive data from app-mqtt-export service
### Reproduce Steps
1. Clone edgex-taf. 
2. Execute the following commands.
```
export export WORK_DIR=${HOME}/edgex-taf
cd ${WORK_DIR}/TAF/utils/scripts/docker
sh run-tests.sh x86_64 true 2
```
### Actual result
Failed Test Case: Export002

Found the following logs on app-mqtt-export service
```
level=DEBUG ts=2021-04-20T03:39:28.975059293Z app=app-mqtt-export source=runtime.go:87 msg="Processing message 2 Transforms"
level=DEBUG ts=2021-04-20T03:39:28.97509852Z app=app-mqtt-export source=runtime.go:111 msg="Pipeline is expecting an AddEventRequest or Event DTO"
level=DEBUG ts=2021-04-20T03:39:28.975134279Z app=app-mqtt-export source=runtime.go:217 msg="Attempting to process Payload as an AddEventRequest DTO"
level=DEBUG ts=2021-04-20T03:39:28.975260882Z app=app-mqtt-export source=runtime.go:224 msg="Using Event DTO from AddEventRequest DTO"
level=DEBUG ts=2021-04-20T03:39:28.975299759Z app=app-mqtt-export source=runtime.go:344 msg="Event Received with ProfileName=Sample-Profile, DeviceName=mqtt-export-device and ReadingCount=1"
level=DEBUG ts=2021-04-20T03:39:28.975332275Z app=app-mqtt-export source=runtime.go:351 msg="Event has no tags"
level=DEBUG ts=2021-04-20T03:39:28.975365066Z app=app-mqtt-export source=runtime.go:364 msg="Reading #1 received with ResourceName=DeviceValue_INT16_RW, ValueType=Int16, Value=`8019`"
level=DEBUG ts=2021-04-20T03:39:28.975398357Z app=app-mqtt-export source=conversion.go:66 msg="Transforming to JSON"
level=DEBUG ts=2021-04-20T03:39:28.975462047Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:29.976823636Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:30.978480672Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:31.980424985Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:32.982282072Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:33.985555728Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:34.987472251Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:35.990664566Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:36.992737334Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:37.994977217Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=DEBUG ts=2021-04-20T03:39:38.997802698Z app=app-mqtt-export source=secrets.go:356 msg="Using Secrets URL of `http://edgex-vault:8200/v1/secret/edgex/app-mqtt-export/mqtt`"
level=ERROR ts=2021-04-20T03:39:39.000004356Z app=app-mqtt-export source=runtime.go:188 error="Error found on handling secrets from underlying data-store: Received a '404' response from the secret store" X-Correlation-ID="unsupported value type" msg="Pipeline function #1 resulted in error"
level=DEBUG ts=2021-04-20T04:07:03.39872246Z app=app-mqtt-export source=secrets.go:345 msg="token is successfully renewed"
```

Note. The app-mqtt-export service will be removed after finishing the script.
The teardown of Export002 has to comment out when recreating the issue

### PR DESCRIPTION
**Pull request by cherrycl**
Push mqtt credential into vault.
Fix #376 
Signed-off-by: Cherry Wang <cherry@iotechsys.com>

### CODE REVIEW

File: TAF/utils/scripts/docker/get-compose-file.sh [hunk 1]
```diff
@@ -32,6 +32,8 @@ if [ "$USE_RELEASE" = "pre-release" ]; then
   if [ "$USE_SECURITY" = "-security-" ]; then
     sed -i "/ROUTES_RULES-ENGINE_HOST/a \ \ \ \ \ \ ADD_PROXY_ROUTE: 'modbusdevice.http://edgex-device-modbus:49991'" \
     docker-compose.yaml
+    sed -i 's/\USERNAME_PLACEH_OLDER/${MQTT_USER}/g' docker-compose.yaml
+    sed -i 's/\PASSWORD_PLACE_HOLDER/${MQTT_PWD}/g' docker-compose.yaml
```
Comment (lenny-intel) [inline TAF/utils/scripts/docker/get-compose-file.sh:36]: These are not needed in secure mode since those place holders are for InsecureSecrets. These would be needed in the non-secure path if securing the broker in non-secure mode.. Also looks like we have typo to fix in `compose builder` source files... ;-)

```
      WRITABLE_INSECURESECRETS_MQTT_SECRETS_PASSWORD: PASSWORD_PLACE_HOLDER
      WRITABLE_INSECURESECRETS_MQTT_SECRETS_USERNAME: USERNAME_PLACEH_OLDER
```
If not needed in non-secure mode, we can remove the placeholder overrides.

**Review by lenny-intel — CHANGES_REQUESTED** [review]

File: TAF/utils/scripts/docker/get-compose-file.sh (hunk 1 above)
Comment (cherrycl) [reply TAF/utils/scripts/docker/get-compose-file.sh]: @lenny-intel Removed the override lines of username and password from the `get-compose-file.sh`. And yes, we don't use username and password in non-secure mode, both of them can be removed. Thank you.

**Review by jinlinGuan — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM
